### ISSUE TITLE
Support for Cookies

### ISSUE THREAD

**Issue by stellarpower** [andrewpillar/req#1]
Nice project! Looks really useful. I have had issues with using Postman before - it's too focussed on testing, and actually doing something with the responses you get back from your APIs is not properly supported, so we can't regress on what our APIs are actually doing.

I do quite a bit of web scraping for projects - I'd like ot be able ot use tihs right now, but one critical feature (hence why I need to script this project) that appears to be missing is cookie support. The API I am querying will refuse to speak to me unless I soak up a couple of cookies for mthe start page. It also looks like there aren't methods that allow me to do string manipulation - so that I also can't extract the cookie for mthe headers returned and then set this manually.

Unless I'm missing somehting, but if it's not possible, thought I'd suggest it. Nice job anyway!

**Comment by andrewpillar** [comment]
I can definitely see the utility in this. At initial glance, this could be achieved if more commands for string manipulation were introduced, but this would be messy. The best approach here may be to extend the `encode`/`decode` commands to allow for working with cookies here, then you could set them in the `Cookie` header, for example,

    Cookie = encode cookie (
        Session: encode base64 "some-user-id"
    );

    Resp = GET "https://api.example.com" (Cookie: $Cookie) -> send;

for working with cookies in the response I'm not too sure, multiple `Set-Cookie` headers could be returned, so these would need to be iterated over then decoding accordingly. Looking at the implementation for the underlying response type, we only return the first value from the headers map we have instead of returning the entire list of values. Not too keen on changing the return of this, or introducing the possibility of it either returning a single value or multiple - it becomes messy.

I will need to think more about how it could be handled when extracting from a response in a way that feels idiomatic to what we already have, and that isn't intrusive into the language.

**Comment by stellarpower** [comment]
Afraid I've not managed to use the lang enough to know what would and wouldn't be a good way of doing it, but I wonder if handling it transparently would be sufficient. Depends if there's enough argument for wanting to manipulate cookies directly, or if conversely, just storing them persistently during the session would keep the library cleaner. I think my usecase would be handled by the latter personally.

**Comment by andrewpillar** [comment]
Ok, started working on a preliminary implementation for working with cookies in response, this is what it looks like so far,

    Resp = GET "https://api.example.com" -> send;
    Cookie = $Resp.Cookie["cookie-name"];

and the `Cookie` type that is returned is basically the `net/http.Cookie` structure from the standard lib of Go. Still need to work out some kinks in this implementation, but it's available on the [cookie][0] branch if you wanna build off that to play with it for a bit.

[0]: https://github.com/andrewpillar/req/tree/cookie

**Comment by andrewpillar** [comment]
More progress has been made, you can see what the API would look like [here][0] for creating cookies and retrieving them too.

[0]: https://github.com/andrewpillar/req/blob/ec4dc1951ce5b61504afea687b498fb2314855a1/eval/testdata/cookie.req

**Comment by andrewpillar** [comment]
Made a new [release][0] that includes support for cookies. Closing this issue, if you have any further problems then feel free to raise a new issue.

[0]: https://github.com/andrewpillar/req/releases/tag/v1.1.0
